// export const BASE_URL = 'https://www.familycarecircle.com/fccApi/2.0/';
export const BASE_URL = 'http://45.79.147.166:8000/fccApi/2.0/'
export const USER_LOGIN = 'userms/login'
export const CREATE_ACCOUNT = 'regms/create'
export const FORGOT_PASSWORD = 'userms/forgetPassword'
export const RESET_PASSWORD = 'userms/resetPassword'
export const VERIFY_ACCOUNT = 'regms/verify'
export const GET_COUNTRIES = 'countryms/getAll'
export const RESEND_OTP = 'regms/verificationCodeRequest';
export const GET_STATES_AND_TIMEZONES = 'timezonems/getForCountry'
